### ISSUE TITLE
MasterPass payment crashing app

### ISSUE THREAD

**Issue by alihassan143** [born-ideas/masterpass-flutter-plugin#1]
when i try to pay through master pass the android app crashes when tap on pay  button

**Comment by alihassan143** [comment]
E/AndroidRuntime(11325): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
E/AndroidRuntime(11325): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
E/AndroidRuntime(11325): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(11325): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(11325): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
E/AndroidRuntime(11325): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(11325): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime(11325): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime(11325): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(11325): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime(11325): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/AndroidRuntime(11325): Caused by: java.lang.SecurityException: getDeviceId: The user 10154 does not meet the requirements to access device identifiers.
E/AndroidRuntime(11325): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
E/AndroidRuntime(11325): 	at android.os.Parcel.createException(Parcel.java:2357)
E/AndroidRuntime(11325): 	at android.os.Parcel.readException(Parcel.java:2340)
E/AndroidRuntime(11325): 	at android.os.Parcel.readException(Parcel.java:2282)
E/AndroidRuntime(11325): 	at com.android.internal.telephony.ITelephony$Stub$Proxy.getDeviceIdWithFeature(ITelephony.java:11479)
E/AndroidRuntime(11325): 	at android.telephony.TelephonyManager.getDeviceId(TelephonyManager.java:1929)
E/AndroidRuntime(11325): 	at com.oltio.liblite.internal.k.a(Unknown Source:31)





that is error i am facing app suddenly crashes when tap on pay  button

**Comment by altafkhan8719** [comment]
getting the same issue,

please also provide detailed documentation on how to integrate into a flutter,

Caused by: java.lang.SecurityException: getDeviceId: The user 10154 does not meet the requirements to access device identifiers.

**Comment by alihassan143** [comment]
It is very simple to implement but this plugin is not working right now i suggest you to try another plugin not this one

**Comment by the-mars-rover** [comment]
Hi @alihassan143  - sorry for the late response but this plugin is no longer being actively supported. We recommend contacting Masterpass directly for the SDK details which can be used for implementing a new plugin.
